import { useParams } from 'react-router-dom';
import { useState, useEffect } from 'react';
import Topbar from '../components/layout/Topbar';
import BarChart from '../components/charts/BarChart';
import Donut from '../components/charts/Donut';
import * as Icons from '../components/icons';
import { spendDays, categorySpend, weeklyInsight, monthlyInsight } from '../lib/sampleData';
import * as api from '../lib/api';
import type { InsightBullet } from '../types';

function highlightHeadline(text: string) {
  const parts = text.split(/(Rs\s[\d,]+|\d+%)/g);
  return parts.map((p, i) => {
    if (/^Rs\s[\d,]+$/.test(p)) return <span key={i} className="accent num">{p}</span>;
    if (/^\d+%$/.test(p)) return <span key={i} className="accent num">{p}</span>;
    return p;
  });
}

function BulletIcon({ icon }: { icon: string }) {
  if (icon === 'arrow-up')   return <Icons.ArrowUp size={14} />;
  if (icon === 'arrow-down') return <Icons.ArrowDown size={14} />;
  if (icon === 'flat')       return <Icons.Flat size={14} />;
  if (icon === 'alert')      return <Icons.AlertCircle size={14} />;
  return <Icons.Stars size={14} />;
}

export default function Insights() {
  const { kind = 'weekly' } = useParams<{ kind: string }>();
  const isWeekly = kind === 'weekly';
  const data = isWeekly ? weeklyInsight : monthlyInsight;
  const chartDays = isWeekly ? spendDays.slice(-7) : spendDays;
  const [apiInsight, setApiInsight] = useState<api.ApiInsight | null>(null);
  const [noInsight, setNoInsight] = useState(false);

  useEffect(() => {
    const type = isWeekly ? 'WEEKLY' : 'MONTHLY';
    api.fetchLatestInsight(type)
      .then(r => setApiInsight(r.data))
      .catch(err => {
        if (err.response?.status === 204 || err.response?.status === 404) setNoInsight(true);
      });
  }, [isWeekly]);

  const vsData = [
    { label: 'Total spend', now: isWeekly ? 34820 : 49499, prev: isWeekly ? 42410 : 56300, lowerBetter: true },
    { label: 'Food & Drink', now: isWeekly ? 2890 : 6720,  prev: isWeekly ? 4200 : 8100,   lowerBetter: true },
    { label: 'Transport',   now: isWeekly ? 490 : 2180,    prev: isWeekly ? 510 : 2050,    lowerBetter: true },
    { label: 'Income',      now: isWeekly ? 28400 : 123400, prev: isWeekly ? 0 : 95000,    lowerBetter: false },
  ];

  return (
    <>
      <Topbar title={isWeekly ? 'Weekly insights' : 'Monthly insights'} crumbs={['Home', 'Insights']} />
      <div className="page page-wide">
        <div className="page-hd">
          <div>
            <h2>{isWeekly ? 'Weekly insights' : 'Monthly insights'}</h2>
            <div className="sub">{data.period} · Generated by AI</div>
          </div>
          <div className="row">
            <button className="btn btn-sm"><Icons.Refresh size={12} /> Regenerate</button>
            <button className="btn btn-sm"><Icons.Download size={12} /> Export</button>
          </div>
        </div>

        <div className="grid" style={{ gridTemplateColumns: '2fr 1fr', alignItems: 'flex-start' }}>
          <div className="col" style={{ gap: 16 }}>
            {/* Headline */}
            <div className="card">
              <div className="card-bd" style={{ padding: 24 }}>
                <div className="row" style={{ gap: 8, marginBottom: 12 }}>
                  <span className="badge acc"><Icons.Stars size={10} /> AI summary</span>
                  {apiInsight && <span style={{ fontSize: 11, color: 'var(--tx-3)' }}>
                    {new Date(apiInsight.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                  </span>}
                </div>
                {apiInsight ? (
                  <div className="insight-body">{apiInsight.insightText}</div>
                ) : noInsight ? (
                  <div style={{ color: 'var(--tx-3)', fontSize: 13 }}>No {kind} insight generated yet. Insights are created automatically every {isWeekly ? 'Monday morning' : '1st of the month'}.</div>
                ) : (
                  <>
                    <div className="insight-headline">{highlightHeadline(data.headline)}</div>
                    <div className="insight-body" style={{ marginTop: 18 }}>{data.summary}</div>
                  </>
                )}
              </div>
            </div>

            {/* Bullets */}
            <div className="card">
              <div className="card-hd">
                <h3>Highlights</h3>
                <div className="sub">{data.bullets.length} things to know</div>
              </div>
              <div className="card-bd" style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 10 }}>
                {data.bullets.map((b: InsightBullet, i) => (
                  <div key={i} className={`bullet ${b.tone}`}>
                    <div className="bullet-ico"><BulletIcon icon={b.icon} /></div>
                    <div className="bullet-text">{b.text}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Chart */}
            <div className="card">
              <div className="card-hd">
                <h3>{isWeekly ? 'Daily spend · this week' : 'Daily spend · this month'}</h3>
                <div className="sub">Each bar = one day</div>
              </div>
              <div className="card-bd">
                <BarChart data={chartDays} height={isWeekly ? 160 : 200} />
              </div>
            </div>
          </div>

          <div className="col">
            {/* Donut */}
            <div className="card">
              <div className="card-hd"><h3>By category</h3></div>
              <div className="card-bd" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 14 }}>
                <Donut data={categorySpend.slice(0, 6)} size={150} />
                <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {categorySpend.slice(0, 6).map((c) => {
                    const total = categorySpend.reduce((s, x) => s + x.amount, 0);
                    const pct = ((c.amount / total) * 100).toFixed(0);
                    return (
                      <div key={c.id} className="row between" style={{ fontSize: 12 }}>
                        <div className="row" style={{ gap: 8, minWidth: 0 }}>
                          <span style={{ width: 8, height: 8, borderRadius: 2, background: c.color, flexShrink: 0 }} />
                          <span style={{ color: 'var(--tx-2)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{c.label}</span>
                        </div>
                        <div className="row" style={{ gap: 8 }}>
                          <span className="num" style={{ color: 'var(--tx-3)', fontSize: 11 }}>{pct}%</span>
                          <span className="num" style={{ fontWeight: 500, minWidth: 60, textAlign: 'right' }}>Rs {(c.amount / 1000).toFixed(1)}k</span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            {/* Vs last */}
            <div className="card">
              <div className="card-hd"><h3>Versus last {isWeekly ? 'week' : 'month'}</h3></div>
              <div className="card-bd" style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {vsData.map((m, i) => {
                  const delta = ((m.now - m.prev) / (m.prev || 1)) * 100;
                  const good = m.lowerBetter ? delta < 0 : delta > 0;
                  return (
                    <div key={i}>
                      <div className="row between" style={{ marginBottom: 4 }}>
                        <span style={{ fontSize: 12, color: 'var(--tx-2)' }}>{m.label}</span>
                        <span className="num" style={{ fontSize: 12, fontWeight: 500 }}>Rs {m.now.toLocaleString('en-IN')}</span>
                      </div>
                      <div className="row between" style={{ fontSize: 11 }}>
                        <span style={{ color: 'var(--tx-4)' }} className="num">prev: Rs {m.prev.toLocaleString('en-IN')}</span>
                        <span style={{ color: good ? 'var(--pos)' : 'var(--neg)' }}>{delta > 0 ? '+' : ''}{delta.toFixed(1)}%</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
